name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: mvn -B clean verify
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: pams-lab2b-jar
          path: target/*-shaded.jar
